// The hero outline, and the projection that puts places on it.
//
// Run with:  npm run outline
//
// Two things here are worth a test rather than a glance.
//
// The projection is the only thing standing between a latitude and a dot, and
// it fails quietly: a wrong scale still draws a plausible-looking constellation
// somewhere on the canvas, and nobody counts dots against a map they have never
// seen. So the corners of the geographic box are pinned to the corners of the
// artwork, and three real places are pinned to coordinates computed once and
// checked by eye against the rendered page.
//
// The outline itself is generated by scripts/09_israel_outline.py, and the
// generation has one trap that has already been fallen into: the compound `PS`
// path holds Gaza and Judea and Samaria as two subpaths, the second beginning
// with a *relative* moveto. Re-anchoring it by rewriting that `m` as `M` also
// silently reinterprets all 175 following linetos as absolute, which scatters
// the shape and draws a diagonal line across the country. The shape assertions
// below are what catch that, because it renders without error.
import {
  ISRAEL_OUTLINE,
  OUTLINE_GEO,
  OUTLINE_HEIGHT,
  OUTLINE_WIDTH,
  isOnOutline,
  projectToOutline,
} from "../src/lib/israel-outline.ts";

let failed = 0;
function check(label, actual, expected) {
  const ok = Object.is(actual, expected);
  if (!ok) {
    failed += 1;
    console.log(`  FAIL  ${label}\n          got  ${actual}\n          want ${expected}`);
  } else {
    console.log(`  ok    ${label}`);
  }
}

const at = (lat, lng) => {
  const p = projectToOutline(lat, lng);
  return `${p.x.toFixed(4)},${p.y.toFixed(4)}`;
};

console.log("projection");

check(
  "the north-west corner of the geo box is the origin",
  at(OUTLINE_GEO.latHi, OUTLINE_GEO.lngLo),
  "0.0000,0.0000",
);
check(
  "the south-east corner is the far corner of the artwork",
  at(OUTLINE_GEO.latLo, OUTLINE_GEO.lngHi),
  `${OUTLINE_WIDTH.toFixed(4)},${OUTLINE_HEIGHT.toFixed(4)}`,
);
check("Tel Aviv lands where it should", at(32.0853, 34.7818), "95.4862,271.5340");
check("Eilat lands near the bottom", at(29.5581, 34.9482), "124.2113,780.2576");
check("Beit El lands east of centre", at(31.9432512, 35.2266116), "172.2725,300.1283");

// Latitude must run north to south down the screen, which is the sign error
// that would otherwise flip the whole country and still look like a country.
check(
  "north is above south",
  projectToOutline(33.0, 35.0).y < projectToOutline(30.0, 35.0).y,
  true,
);
check(
  "east is right of west, before RTL flips the box",
  projectToOutline(32.0, 35.5).x > projectToOutline(32.0, 34.5).x,
  true,
);

console.log("\nbounds guard");
check("the origin is on the artwork", isOnOutline(0, 0), true);
check("the far corner is on the artwork", isOnOutline(OUTLINE_WIDTH, OUTLINE_HEIGHT), true);
check("a point west of the coast is not", isOnOutline(-0.01, 100), false);
check("a point south of Eilat is not", isOnOutline(100, OUTLINE_HEIGHT + 0.01), false);
// Cyprus, which is what a longitude typo tends to produce.
check("somewhere in the sea is rejected", isOnOutline(...Object.values(projectToOutline(35.1, 33.4))), false);

console.log("\nthe outline");

check("every district is present", ISRAEL_OUTLINE.length, 8);

const centroid = (d) => {
  const xs = [...d.matchAll(/[ML] (-?[\d.]+),/g)].map((m) => Number(m[1]));
  const ys = [...d.matchAll(/[ML] -?[\d.]+,(-?[\d.]+)/g)].map((m) => Number(m[1]));
  const cx = xs.reduce((a, b) => a + b, 0) / xs.length;
  const cy = ys.reduce((a, b) => a + b, 0) / ys.length;
  return {
    lng: OUTLINE_GEO.lngLo + (cx / OUTLINE_WIDTH) * (OUTLINE_GEO.lngHi - OUTLINE_GEO.lngLo),
    lat: OUTLINE_GEO.latHi - (cy / OUTLINE_HEIGHT) * (OUTLINE_GEO.latHi - OUTLINE_GEO.latLo),
  };
};

check(
  "every path is absolute, so no leading command can be misread",
  ISRAEL_OUTLINE.every((s) => s.d.startsWith("M ") && !/[mlhvcsqtaz] /.test(s.d)),
  true,
);
check(
  "every path is closed",
  ISRAEL_OUTLINE.every((s) => s.d.endsWith(" Z")),
  true,
);
check(
  "every path stays inside the artwork",
  ISRAEL_OUTLINE.every((s) =>
    [...s.d.matchAll(/[ML] (-?[\d.]+),(-?[\d.]+)/g)].every((m) =>
      isOnOutline(Number(m[1]), Number(m[2])),
    ),
  ),
  true,
);

// Judea and Samaria stays: בית אל, שילה and מעלה אדומים are all there and all
// have places in the corpus. Its centroid sits around 35.23E 32.00N.
check(
  "Judea and Samaria is drawn",
  ISRAEL_OUTLINE.some((s) => {
    const c = centroid(s.d);
    return c.lng > 35.0 && c.lng < 35.5 && c.lat > 31.7 && c.lat < 32.3;
  }),
  true,
);

// Gaza comes out. Its centroid is around 34.39E 31.40N, and nothing else in
// the file is anywhere near there.
check(
  "Gaza is not",
  ISRAEL_OUTLINE.some((s) => {
    const c = centroid(s.d);
    return c.lng < 34.6 && c.lat > 31.2 && c.lat < 31.6;
  }),
  false,
);

console.log(failed === 0 ? "\nall cases passed" : `\n${failed} failures`);
process.exit(failed === 0 ? 0 : 1);
